version: "3.9"

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data # データ永続化のためのボリューム
    ports:
      - "5432:5432" # PostgreSQLのデフォルトポート
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1 # PostgreSQLのヘルスチェック
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env.prod # 環境変数ファイルの読み込み

  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    volumes:
      - .:/code # ソースコードのマウント
      - ./static:/static # 静的ファイルのマウント
    expose:
      - "8000" # Djangoのデフォルトポート
    command: sh -c "/usr/local/bin/entrypoint.sh" # エントリーポイントスクリプトの実行
    env_file:
      - .env.prod # 環境変数ファイルの読み込み
    depends_on:
      db:
        condition: service_healthy # dbサービスがヘルシーであることを条件とする

  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static # 静的ファイルのマウント
    ports:
      - "80:80" # Nginxのデフォルトポート
    depends_on:
      - app # appサービスが起動していることを条件とする

volumes:
  db_data: # PostgreSQLデータ用ボリューム
  static: # 静的ファイル用ボリューム
